name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
  
    - name: Login to Docker HUB
      uses: docker/login-action@v3
      with:
          username: "gabrielsh38"
          password: "dckr_pat_L1Dayp-igsHW9oRhlP8NKfkHaf0"

    - name: Build  
      run: |
        docker build ./prolor/Application/api/ -t gabrielsh38/dockerbuild:latest       

    - name: Push Docker HUB  
      run: |
        docker tag gabrielsh38/dockerbuild:latest gabrielsh38/dockerbuild:latest
        docker push gabrielsh38/dockerbuild:latest  
